var arr = [
"UNLOAD THE TOAD",
"WTF 2 SHENS?",
"JUSTICE RAINS FROM AHHHHHHHHHHH",
" Iâ€™ll have two number 9s, a number 9 large, a number 6 with extra dip, a number 7, two number ",
"Fighting for a brighter tomorrow",
"QUAAAADRA KILL",
"ENEMY YASUO > OUR YASUO",
"brb pizzaâ€™s at the door",
"A summoner has disconnected",
"Boosted animals ... all of u",
"Regi is a nice guy",
"Riot games killing memes by releasing heavily demanded features",
"SPINNNNNN TO WIN",
"BLUE CARD REGI BLUE CARD",
"LUL GROSS GORE BANNED BETER TF THEN REGI LUL",
"KappaPride",
"SneakyGasm",
"SNEAKY DADDY GIVE IT TO ME",
"Regi eyebrows MIA",
"Is that Regi or Wukong??",
"RIOT KILLING ALL OUR MEMES?",
"YOU KNOW I HAD TO DO IT TO EM",
"CAN I GET UHHHHHHHHHH",
"YO I JUST NUTTED ALL OVER THIS MID LANER",
"WHEREâ€™S THE TEAM???",
"Farming jungler gg",
"LOL LOCKING IN UDYR TRICK2G IN 2K17",
"Delta Fox is a good team guys",
"IMAQTPIE #1 ADC IN NA LMAOOOOO",
"XSPECIAL WAS THE PROBLEM. SANTORIN WAS THE PROBLEM. TURTLE WAS THE PROBLEM",
"GG we have a Hanzo",
"NERF THIS",
"Iâ€™m a professional Super Smash Bros Melee player and I main Ness.",
"ITS A PRO GENJI",
"FeelsBadMan NA at worlds FeelsBadMan",
"TSM AT MSI LUL",
"THE GAP IS CLOSING LUL",
"Kkoma finding a wife",
"I miss the old Voyboy, SoloQ troll Voyboy. Not playing tanks Voyboy, teamfight flanks Voyboy. I hate the new Voyboy, the never rude Voyboy, family friendly streams Voyb",
"HELLO? Computer repairman?? This is QT.  Monitor always grey need you to fix",
"à¼¼ ã¤ â—•_â—• à¼½ã¤ TSM TAKE MY ENERGY à¼¼ ã¤ â—•_â—• à¼½ã¤",
"à¼¼ ã¤ â—•_â—• à¼½ã¤ FNATIC TAKE MY ENERGY à¼¼ ã¤ â—•_â—• à¼½ã¤",
"à¼¼ ã¤ â—•_â—• à¼½ã¤ C9 TAKE MY ENERGY à¼¼ ã¤ â—•_â—• à¼½ã¤",
"à¼¼ ã¤ â—•_â—• à¼½ã¤ COMPLEXITY GAMING TAKE MY ENERGY à¼¼ ã¤ â—•_â—• à¼½ã¤",
"à¼¼ ã¤ â—•_â—• à¼½ã¤ XDG TAKE MY ENERGY à¼¼ ã¤ â—•_â—• à¼½ã¤",
"à¼¼ ã¤ â—•_â—• à¼½ã¤ WILD TURTLE TAKE MY ENERGY à¼¼ ã¤ â—•_â—• à¼½ã¤",
"1000 IQ plays",
"SUMMIT MOLLY LUL",
"PEKE PEKE PEKE PEKE oh shit im dead",
"No one has ever done that in the history of Dota",
"NOW DESTINYS CALLING OUT UR NAME SO REPLY SO REPLYYYYYYY AND IGNITE",
"Ultimate bravery in ranked is the only way to play ranked",
"Nerfing Ireliaâ€¦ again...",
"Channeling Karthus R",
"Waiting for High Noon",
"Kicking your brudda in the ass",
"SMARTZZZ",
"DUMBZZZZZZZ",
"SHIT TRISTANA IS PRETTY GOOD. BETTER NERF IRELIA",
"Widow in 2017 lul",
"What do you mean my build sucks?? Mobafire says its good >:(",
"#FreeTyler1",
"Teams banned Morde at worlds lul",
"IMMA LET U FINISH. BUT. IMAGINE DRAGONS HAD THE BEST WORLDS THEME OF ALL TIMEEEEEEEEE",
"Iâ€™M IN CHAAAAARGE NOWWW",
"EVERYONE, GET IN HERE",
"I AM LOADING INCARNATE",
"Not even close to loading baby",
"Calculated",
"Topdecking lethal",
"FUN AND INTERACTIVE CHAMPION NICE JOB RIOT",
"Preparing the fnatic brush",
"FK IT, BAYLIFE",
"I NEED HEALING",
"Cannon rushing IN 2k17 LUL",
"Notice me Faker senpai",
"VAYNE VAYNE VAYNE VAYNE VAYNE VAYNE VAYNE VAYNE",
"ODD ONE WAS THE PROBLEM LUL",
"SORAKA GIVE ME MANA. oh waitâ€¦.",
"Did he just walk up... slowlyâ€¦ and meme?",
"BOBBY SCAR 6TH AT GENESIS???",
"PPMD COME BACK",
"HBOX LEDGE CAMPING LIMIT LUL",
"DAIGO THE GOD UMEHARA",
"Itâ€™s fast, itâ€™s fun, itâ€™s Dominion.",
"My bruddah got duh beat by HotShotNidaleeGG. He kick my bruddah in de ass. He was praying duh Lee Singah.",
"Double rainbow? What does it mean?",
"Loading screens in 2017 LUL",
"Monte and Doa died for Sandbox mode.",
"COOL. CALM. COLLECTED. - Bobby Scarnewman",
"TOOOOPH! DID YOU SEE THE READS???",
"Brainstorming for Ryzeâ€™s next rework.",
"ADC IN 2017 LUL",
"Buffing Trinity Force before worlds.",
"Brb releasing juggernauts before worlds lul",
"Sneaky in lane LUL",
"Riot Games is a small startup company.",
"Per se. RAFFFFFFF LOOOOL hello BAD MEME BUDDY UR GNNA GET BANNED ..per se ",
"YEYUHHHZZZZZZ",
"Buffing Corki before Worlds.",
"Respect your elders",
"Imaqtpie > Doublelift",
"Loading 5 point 5 fking k bytes",
"Support is so EASY",
"#FreeTyler1",
"RUN IT DOWN MID",
"Imaqtpie > Faker",
"DOUBLELIFTUUUUUUUU PENTA KEEEEEEEEL",
"TSM TSM TSM TSM TSM TSM TSM",
"NA > EU",
"Gunning down the degenerates",
"â˜ DARSHOFF â˜’ DARSHON",
"Did TSM wonned?",
"UNINHIBIT THE RIBBIT",
"UNBENCH THE KENCH",
"UNCLOG THE FROG",
"WildTurtle if you see this I legit love you",
"RITO GAMES HIRE ME PLS",
"O-oooooooooo AAAAE-A-A-I-A-U- JO-oooooooooooo AAE-O-A-A-U-U-A- E-eee-ee-eee AAAAE-A-E-I-E-A-JO-ooo-oo-oo-oo EEEEO-A-AAA-AAAA",
"( Í¡Â° Íœâ—¯ Í¡Â°) ï»¿ï¼£ï¼¬ï¼¯ï¼·ï¼® ï¼¦ï¼©ï¼¥ï¼³ï¼´ï¼¡ ( Í¡Â° Íœâ—¯ Í¡Â°)",
"8=====> Only the chosen one can hold this donger",
"BabyRage NEVER LUCKY BabyRage",
"Hey guys, this is my very first MEME. Thanks for listening!",
"u r a boosted animal",
"WORTHHHHHHHHHHHH",
"DIG Baron???",
"CLG FINED 5 point 5 fking k",
"PPMD KREYGASM",
"MANGO USA MANGO USA MANGO USA",
"Ordering to-go from Bjergerking...",
"Resolving fkin bugsplat... again",
"Finding more key fragments...",
"Facechecking baron...",
"Will this site get me a girlfriend??",
"MOM I CAN'T PAUSE LEAGUE OF LEGENDS I'VE TOLD YOU THIS BEFORE",
"RIP HARAMBE 1 YEAR LATER :(",
"Savage memes can't melt playoff dreams",
"Who the fk put Mordekaiser in the botlane?",
"I love brasilions they be speakin porch of geese n I be like damn mami"
];


var item = arr[Math.floor(Math.random()*arr.length)];
document.getElementById('load').innerHTML = item